/*
#########################################################################
# _sub_genotypeqc_report
# subroutine for genotypeqc
# command: _sub_genotypeqc_report
# =======================================================================
# Author: Richard Anney
# Institute: Cardiff University
# E-mail: AnneyR@cardiff.ac.uk
# Date: 12th July 2017
#########################################################################
*/
program _sub_genotypeqc_report
syntax  
end

	noi di as text"...creating quality-control-report.docx"
	global toc    "$S_DATE $S_TIME"
	!del ${sub_mod_output}-quality-control-report.docx
	//open document
	mata:
	dh = _docx_new()
	// set default document font, size, color, and orientation
	_docx_set_color(dh, "000000")
	_docx_set_font(dh, "Consolas")
	_docx_set_size(dh, 18)

	// TITLE PAGE
	_docx_paragraph_new(dh, "")
	_docx_paragraph_add_text(dh, "# Genotype Array Quality Control Report")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# This report was created via the program -genotypeqc-")  
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# Author .............................. Richard Anney (anneyr@cardiff.ac.uk)")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# Downloaded from ..................... https://github.com/ricanney")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Run Date ......................... $S_DATE $S_TIME")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Quality Control Version .......... v6")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > Input File: ...................... ${data_input}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Input Array: ..................... $arrayType")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Output File ............. ........ ${data_input}-qc-v6")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Input Total Markers: ............. $count_markers_1")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Input Total Individuals: ......... $count_individ_1")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Output Total Markers ............. $count_markers_3")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Output Total Individuals ......... $count_individ_3")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > CEU/ TSI-like Individuals ........ $count_European")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# THRESHOLDS")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > maximum missing by individual ..... $mind")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > maximum missing by marker ......... $geno2")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > minimum minor allele frequency .... mac 5")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > maximum hardy-weinberg deviation .. 10e-$hwep")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > maximum heterozygosity deviation .. $hetsd x sd" )
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > rounds of QC ...................... $rounds")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)

	// REPORTING GENOME BUILD 
	_docx_paragraph_new(dh, "")
	_docx_add_pagebreak(dh,)
	_docx_paragraph_set_textsize(dh, 18)
	_docx_paragraph_add_text(dh, "# Genome builds")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "This data was created using the program -bim2build-. ")  
	_docx_paragraph_add_text(dh, "This program reports the genome build of the input data. As part of the QC pipeline all data is converted to hg19 +1. Below is a plot jaccard index for the different genome builds for the input data. The output data is reported as a confirmation/ sanity check.")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Genome build of ${data_input} (input binaries)")
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${input}.hg-buildmatch.png")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Genome build of ${data_input}-qc-v6 (output binaries)")
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"tempfile-module2-processed.hg-buildmatch.png")

	// REPORTING ARRAY
	_docx_paragraph_new(dh, "")
	_docx_add_pagebreak(dh,)
	_docx_paragraph_set_textsize(dh, 18)	
	_docx_paragraph_add_text(dh, "# Identifying the genotyping array")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "This subset was created using the program -bim2array- (under development). This program assesses the genotype-array against a panel of known arrays. Most of the data used to cross reference comes from the data reported here (http://www.well.ox.ac.uk/~wrayner/strand/). Importantly, these are only the best estimates based on overlap coefficients. Below is a plot the jaccard index for the top ten matched arrays.")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Array match for input binaries is  ${arrayType}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Match metrics (Jaccard Index)    = ${Jaccard}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Array match of ${data_input}")
	_docx_image_add(dh,"${input}.arraymatch.png")
	
	// REPORTING ALLELE-FREQUENCY DIFFERENCES
	_docx_paragraph_new(dh, "")
	_docx_add_pagebreak(dh,)
	_docx_paragraph_set_textsize(dh, 18)
	_docx_paragraph_add_text(dh, "# Compare allele-frequency to reference")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "As part of the quality-control protocol, the imported variant names are sometimes converted to rsid. This is achieved by mapping to a 1000-genomes dataset as a reference. The mapping is based on chromosome location and genotype (based on compatible UIPAC genotype codes, for example R genotypes are compatible with R or Y). The program runs a sanity-check for the merge using allele-frequencies. After matching to strand/ allele we can plot frequencies to identify discrepancies between the allele frequencies reported in the test and reference dataset. As a precaution markers with > 10% allele-frequency differences are dropped. Below is a plot the pre and post qc allele frequency scatter plots.")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Scatter-plot of allele frequencies against reference")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"tempfile-module2-allele-frequency-check.png")

	// DISPLAYING ANCESTRY DISTRIBUTIONS   
	_docx_paragraph_new(dh, "")
	_docx_add_pagebreak(dh,)
	_docx_paragraph_set_textsize(dh, 18)
	_docx_paragraph_add_text(dh, "# Plotting ancestry PCA with hapmap reference")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "This subset was created using the program -bim2hapmap-. These plots are created from the *.eigenval files created using the --pca flag in plink. As part of the program we also define a subset of individuals who are defined as ${like}-like. This is based on similarity of the genotypes to hapmap reference genotypes. In this instance we flag individuals who for the top-3 PCs are no more than 2.5 standard deviations from that reported by the ${like} hapmap3 populations. Individuals are not removed, but flagged in the *_${like}-like.keep file. This can be used directly in plink using the --keep flag. Below we plot two panels of PCA plots (PC Scree-Plot; PC1 v PC2; PC1 v PC3; PC2 v PC3). The top panel includes all individuals, whereas the bottom panel focuses on the regions around the ${like} populations. ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > PCA for all ancestries")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"bim2hapmap_pca.png")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > PCA for ancestries (focused aroung ${like}")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"bim2hapmap_pca-${like}-like.png")

	// DISPLAYING CHROMOSOME DISTRIBUTION  
	_docx_paragraph_new(dh, "")
	_docx_add_pagebreak(dh,)
	_docx_paragraph_set_textsize(dh, 18)
	_docx_paragraph_add_text(dh, "# Plotting chromosome distributions")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "The following plots show the distribution of markers by chromosome. This is a useful sanity-check on your data to make sure all chromosomes were included in the final report.")	
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > Distribution by chromosome")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${sub_mod_output}-chromosomes.png")

	// REPORTING RELATEDNESS
	_docx_paragraph_new(dh, "")
	_docx_add_pagebreak(dh,)
	_docx_paragraph_set_textsize(dh, 18)
	_docx_paragraph_add_text(dh, "# Plotting kinship distributions")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "These plots are created from the *.kin0 files created using the --make-king-table flag in plink2. The following plots show relatedness as defined by this kinship matrix. Approximation of kinship thresholds (duplicates, 2nd and 3rd degree relatives) are given by horizontal red lines. As part of the quality control pipeline I have decided to remove -related- individuals at this stage. Individuals with excessive relatedness (indicative of genotyping error) are removed. Use the -bim2unrelated- (underdevelopment) to identify an unrelated subset for downstream analysis.")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > Proportion of Zero IBS by Kinship")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${sub_mod_output}-KIN0_1.png")
	_docx_add_pagebreak(dh,)
	_docx_paragraph_add_text(dh, "# > Histogram of Kinship")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${sub_mod_output}-KIN0_2.png")

	// REPORTING HETEROZYGOSITY
	_docx_paragraph_new(dh, "")
	_docx_add_pagebreak(dh,)
	_docx_paragraph_set_textsize(dh, 18)
	_docx_paragraph_add_text(dh, "# Plotting heterozygosity distributions")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "These plots are created from the *.het files created using the --het flag in plink. The --het flag computes observed and expected autosomal homozygous genotype counts for each sample, and reports method-of-moments F coefficient estimates i.e.")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "([observed hom. count] - [expected count])")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "------------------------------------------")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "([total observations] - [expected count])")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
 	_docx_paragraph_add_text(dh, "Excessive heterozygosity can be indicative of mixed DNA samples, excessive homozygosity can be indicative of poor DNA quality and allele drop-out. In this pipeline, we exclude individuals whose rate of heterozygosity deviates from the population (of genotyping array) mean. Importantly, heterozygosity rates differ on genotyping arrays and within individuals of differing ancestries. Where there are mixed ancestry samples, you may consider relaxing the threshold and excluding only those individuals with extreme deviations from the sample mean")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Distribution of heterozygosity scores per individual")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${sub_mod_output}-HET.png")

	// REPORTING HARDY-WEINBERG EQUILIBRIUM
	_docx_paragraph_new(dh, "")
	_docx_add_pagebreak(dh,)
	_docx_paragraph_set_textsize(dh, 18)
	_docx_paragraph_add_text(dh, "# Plotting hardy-weinberg deviation")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "These plots are created using the --hardy flag in plink. The --hardy flag writes a list of genotype-counts and Hardy-Weinberg equilibrium exact test statistics to plink.hwe. Importantly, we apply less stringent thresholds than in other routines as case samples, by design, may incur HW bias due to disease selection.")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Distribution of hardy-weinberg deviation per marker")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${sub_mod_output}-HWE.png")

	// REPORTING MISSINGNESS
	_docx_paragraph_new(dh, "")
	_docx_add_pagebreak(dh,)
	_docx_paragraph_set_textsize(dh, 18)
	_docx_paragraph_add_text(dh, "# Plotting missingness by individual")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh) 	
	_docx_paragraph_add_text(dh, "These plots are created using the --missing flag in plink. The missing --missing produces sample-based and variant-based missing data reports.")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Distribution of missingness by individual")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${sub_mod_output}-IMISS.png")	
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh) 

	// REPORTING MISSINGNESS
	_docx_paragraph_new(dh, "")
	_docx_add_pagebreak(dh,)
	_docx_paragraph_set_textsize(dh, 18)
	_docx_paragraph_add_text(dh, "# Plotting missingness by variant")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "These plots are created using the --missing flag in plink. The missing --missing produces sample-based and variant-based missing data reports. As part of the pipeline we apply two --geno parameters during the QC pipeline to remove firstly excessive missing then completing the pipeline with a stricter limit")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Distribution of missingness by variant")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${sub_mod_output}-LMISS.png")	

	// REPORTING ALLELE FREQUENCY
	_docx_paragraph_new(dh, "")
	_docx_add_pagebreak(dh,)
	_docx_paragraph_set_textsize(dh, 18)
	_docx_paragraph_add_text(dh, "# Plotting minor allele frequency")
	_docx_paragraph_add_linebreak(dh)  
	_docx_paragraph_add_text(dh, "These plots are created using the --freq counts flag. A standard mac 5 flag was added to version 5 of the QC report.")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Distribution of minor allele frequencies")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${sub_mod_output}-FRQ.png")

	// SAVING DOCX
	_docx_save(dh, "${sub_mod_output}-quality-control-report.docx", 1)
	_docx_close(dh)
	end
	
