/*
#########################################################################
# _sub_genotypeqc_report
# subroutine for genotypeqc
# command: _sub_genotypeqc_report
# =======================================================================
# Author: Richard Anney
# Institute: Cardiff University
# E-mail: AnneyR@cardiff.ac.uk
# Date: 12th July 2017
#########################################################################
*/
program _sub_genotypeqc_report
syntax
end
	global toc    "$S_DATE $S_TIME"
	//open document
	mata:
	dh = _docx_new()
	// set default document font, size, color, and orientation
	_docx_set_color(dh, "000000")
	_docx_set_font(dh, "Consolas")
	_docx_set_size(dh, 18)

	// TITLE PAGE
	_docx_paragraph_new(dh, "")
	_docx_paragraph_add_text(dh, "# Genotype Array Quality Control Report")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# This report was created via the program -genotypeqc-")  
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# Author .............................. Richard Anney (anneyr@cardiff.ac.uk)")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# Downloaded from ..................... https://github.com/ricanney")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Run Date ......................... $S_DATE $S_TIME")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Quality Control Version .......... ${version}")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > Input File: ...................... ${input}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Input Array: ..................... ${bim2array}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Output File ............. ........ ${output}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Input Total Markers: ............. ${input_snp}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Input Total Individuals: ......... ${input_ind}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Output Total Markers ............. ${output_snp}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Output Total Individuals ......... ${output_ind}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > CEU/ TSI-like Individuals ........ ${ancestry_ind}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# THRESHOLDS")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > maximum missing by individual ..... ${mind}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > maximum missing by marker ......... ${geno2}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > minimum minor allele frequency .... mac 5")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > maximum hardy-weinberg deviation .. 10e-${hwep}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > maximum heterozygosity deviation .. ${hetsd} x sd" )
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > rounds of QC ...................... ${rounds}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# GENOME BUILD")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > This data was created using the program -bim2build-. ") 
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > This program reports the genome build of the input data. As part of the QC ") 
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > pipeline all data is converted to hg19 +1.")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# GENOTYPE ARRAY")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > This subset was created using the program -bim2array- (under development). This ") 
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > program assesses the genotype-array against a panel of known arrays. Most of the ") 
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > data used to cross reference comes from the data reported here ") 
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > (http://www.well.ox.ac.uk/~wrayner/strand/). Importantly, these are only the best ") 
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > estimates based on overlap coefficients. Below is a plot the jaccard index for the  ") 
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > top ten matched arrays.")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > BEST GUESS ARRAY .................. ${bim2array}")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "")
	_docx_add_pagebreak(dh,)

	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# COMPARISON OF ALLELE FREQUENCIES")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > As part of the quality-control protocol, the imported variant names are sometimes")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > converted to rsid. This is achieved by mapping to a 1000-genomes dataset as a ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > reference. The mapping is based on chromosome location and genotype (based on ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > compatible UIPAC genotype codes, for example R genotypes are compatible with R or ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > Y). The program runs a sanity-check for the merge using allele-frequencies. After ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > matching to strand/ allele we can plot frequencies to identify discrepancies between ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > the allele frequencies reported in the test and reference dataset. As a precaution ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > markers with > 10% allele-frequency differences are dropped. Below is a plot the pre ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > and post qc allele frequency scatter plots.")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > COMPARISON OF MATCHED ALLELE FREQENCIES ")
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"tempfile-4-01-preclean-bim2frq_compare.png")
	_docx_add_pagebreak(dh,)

	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# COMPARISON OF ANCESTRIES")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > This was created using the program -bim2hapmap-. These plots are created from the")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > *.eigenval files created using the --pca flag in plink. As part of the program ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > we also define a subset of individuals who are defined as ${like}-like. This is ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > based on similarity of the genotypes to hapmap reference genotypes. In this instance")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > we flag individuals who for the top-3 PCs are no more than 2.5 standard deviations")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > from that reported by the ${like} hapmap3 populations. Individuals are not removed,")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > but flagged in the *_${like}-like.keep file. This can be used directly in plink ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > using the --keep flag. Below we plot two panels of PCA plots (PC Scree-Plot; PC1 v ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > PC2; PC1 v PC3; PC2 v PC3). The top panel includes all individuals, whereas the ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > bottom panel focuses on the regions around the ${like} populations. ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > PCA FOR ALL ANCESTRIES")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"bim2hapmap_pca.png")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > PCA FOCUSED AROUND THE ${like} SUBSET")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"bim2hapmap_pca-${like}-like.png")
	_docx_add_pagebreak(dh,)

	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# CHROMOSOME DISTRIBUTIONS")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > The following plots show the distribution of markers by chromosome. This is a ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > useful sanity-check on your data to make sure all chromosomes were included in ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > the final report.")	
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > DISTRIBUTIONS OF CHROMOSOMES")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${output}-chromosomes.png")
	_docx_add_pagebreak(dh,)

	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# KINSHIP DISTRIBUTIONS")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > These plots are created from the *.kin0 files created using the --make-king-table")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > flag in plink2. The following plots show relatedness as defined by this kinship ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > matrix. Approximation of kinship thresholds (duplicates, 2nd and 3rd degree ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > relatives) are given by horizontal red lines. As part of the quality control ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > pipeline I have decided to remove -related- individuals at this stage. Individuals ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > with excessive relatedness (indicative of genotyping error) are removed. Use the ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > -bim2unrelated- (underdevelopment) to identify an unrelated subset for downstream ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > analysis.")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > PROPORTION OF ZERO IBS BY KISHIP")	
	_docx_image_add(dh,"${output}-KIN0_1.png")
	_docx_paragraph_add_text(dh, "# > HISTOGRAM OF KINSHIP")	
	_docx_image_add(dh,"${output}-KIN0_2.png")
	_docx_add_pagebreak(dh,)

	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# HETEROZYGOSITY DISTRIBUTIONS")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > These plots are created from the *.het files created using the --het flag in ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > plink. The --het flag computes observed and expected autosomal homozygous ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > genotype counts for each sample, and reports method-of-moments F coefficient ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > estimates i.e.")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "([observed hom. count] - [expected count])")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "------------------------------------------")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "([total observations] - [expected count])")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, " ")
	_docx_paragraph_add_linebreak(dh)
 	_docx_paragraph_add_text(dh, "# > Excessive heterozygosity can be indicative of mixed DNA samples, excessive ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > homozygosity can be indicative of poor DNA quality and allele drop-out. In this ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > pipeline, we exclude individuals whose rate of heterozygosity deviates from the ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > population (of genotyping array) mean. Importantly, heterozygosity rates differ ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > on genotyping arrays and within individuals of differing ancestries. Where there ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > are mixed ancestry samples, you may consider relaxing the threshold and excluding ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > only those individuals with extreme deviations from the sample mean")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > DISTRIBUTION OF HETEROZYGOSITY SCORES IN SAMPLE")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${output}-HET.png")
	_docx_add_pagebreak(dh,)

	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# HARDY WEINBERG DISTRIBUTIONS")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > These plots are created using the --hardy flag in plink. The --hardy flag writes")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > a list of genotype-counts and Hardy-Weinberg equilibrium exact test statistics to ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > plink.hwe. Importantly, we apply less stringent thresholds than in other routines ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > as case samples, by design, may incur HW bias due to disease selection.")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > DISTRIBUTION OF HWE-P PER SNP")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${output}-HWE.png")
	_docx_add_pagebreak(dh,)

	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# MISSINGNESS BY INDIVIDUAL")
	_docx_paragraph_add_linebreak(dh) 	
	_docx_paragraph_add_text(dh, "# > These plots are created using the --missing flag in plink. The missing --missing ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > produces sample-based and variant-based missing data reports.")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > DISTRIBUTION OF IMISS")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${output}-IMISS.png")
	_docx_add_pagebreak(dh,)

	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# MISSINGNESS BY SNP")
	_docx_paragraph_add_linebreak(dh) 
	_docx_paragraph_add_text(dh, "# > These plots are created using the --missing flag in plink. The missing --missing ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > produces sample-based and variant-based missing data reports. As part of the ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > pipeline we apply two --geno parameters during the QC pipeline to remove firstly ")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > excessive missing then completing the pipeline with a stricter limit")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > DISTRIBUTION OF LMISS")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${output}-LMISS.png")
	_docx_add_pagebreak(dh,)

	_docx_paragraph_add_text(dh, "# =================================================================================")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# ALLELE FREQUENCY")
	_docx_paragraph_add_linebreak(dh)  
	_docx_paragraph_add_text(dh, "# > These plots are created using the --freq counts flag. A standard mac 5 flag was ")
	_docx_paragraph_add_linebreak(dh)  
	_docx_paragraph_add_text(dh, "# > added to version 5 of the QC report.")
	_docx_paragraph_add_linebreak(dh)
	_docx_paragraph_add_text(dh, "# > DISTRIBUTION OF ALLELEL FREQUENCIES")	
	_docx_paragraph_add_linebreak(dh)
	_docx_image_add(dh,"${output}-FRQ.png")

	// SAVING DOCX
	_docx_save(dh, "output_folder}\${output}-quality-control-report.docx", 1)
	_docx_close(dh)
	end
	
