program genotypeqc2report_subroutine
syntax
end
mata:
dh = _docx_new()
// set default document font, size, color, and orientation
_docx_set_color(dh, "000000")
_docx_set_font(dh, "Consolas")
_docx_set_size(dh, 18)

// TITLE PAGE
_docx_paragraph_new(dh, "")
_docx_paragraph_add_text(dh, "# GENOTYPE ARRAY QUALITY CONTROL REPORT")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# This report was created via the program -genotypeqc2report- following the -genotypeqc- routine")  
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# AUTHOR ..................... Richard Anney (anneyr@cardiff.ac.uk)")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# SOURCE AVAILABLE FROM ...... https://github.com/ricanney")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# STARTED .................... $S_DATE $S_TIME")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# USERNAME ................... `c(username)'")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# OPERATING SYSTEM ........... `c(os)'")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# VERSION .................... -genotypeqc- ${version}")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > INPUT FOLDER ............. ${path2file_folder}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > INPUT BINARIES ........... ${path2file_file}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > OUTPUT BINARIES .......... ${path2file_file}-qc-${version}")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > ROUNDS OF QC ............. ${rounds}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > REFERENCE GENOTYPES ...... ${ref}")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# > --mac (threshold) ........ 5")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > --geno (threshold) ....... ${geno1};${geno2}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > --mind (threshold) ....... ${mind}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > --hardy (threshold) ...... 1e-${hwep}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > --het (threshold) ........ ${hetsd}) x std.dev from sample mean")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > kinship .................. dup = ${kin_d}; 1st = ${kin_f}; 2nd = ${kin_s}; 3rd = ${kin_t}")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > INPUT BINARIES ARRAY ..... ${bim2array_array}; JACCARD = ${bim2array_jaccard}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > INPUT BINARIES BUILD ..... ${bim2build_input}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > INPUT BINARIES N(SNP) .... ${snp_input}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > INPUT BINARIES N(IND) .... ${ind_input}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > OUTPUT BINARIES BUILD .... ${bim2build_output}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > OUTPUT BINARIES N(SNP) ... ${snp_output}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > OUTPUT BINARIES N(IND) ... ${ind_output}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > ANCESTRY LIKE ............ ${ancestry_like}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# > ANCESTRY LIKE N(IND) ..... ${ancestry_like_n}")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_add_pagebreak(dh,)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# GENOME BUILD")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "This genome build of the input array is assessed using an rsid comparison using the program -bim2build-. The input binaries in this analysis was observed as ${bim2build_input}. As part of the -genotypeqc- routine all output binaries are converted to hg19+1.")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# GENOTYPE ARRAY")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "The genotyping array platform is assessed using a snpid comparison using the program -bim2array-. Using snpid (over rsid) allows identification of non rsid arrays such as affy. The program assesses the genotype-array against a panel of known arrays, most of which were sourced and adapted from the resources made available at (http://www.well.ox.ac.uk/~wrayner/strand/). Importantly, these are only the best estimates based on overlap coefficients. The best guess array for this analysis is ${bim2array_array} (observed with a jaccard-index of ${bim2array_jaccard}.")
_docx_add_pagebreak(dh,)
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# COMPARISON OF ALLELE FREQUENCIES")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "The imported snpid/rsid are sometimes converted to rsid via a reference (via the loc_name (a variable containing chr-hg19+1 position-genotype code)). The -genotypeqc- pipeline uses -bim2frq_compare- to compare the resultant allele frequencies against a reference set of genotypes. After matching to strand/ allele we plot frequencies to identify discrepancies between the allele frequencies reported in the test and reference dataset. As a precaution markers with > 10% allele-frequency differences are dropped. As a point of caution, ancestry mismatches between the reference and test datasets can lead to erroneous exclusion. The reference genotypes for this analysis are ${ref}.")
_docx_paragraph_add_linebreak(dh)
_docx_image_add(dh,"..${delimit}${path2file_file}-qc-${version}${delimit}genotypeqc_data${delimit}bim2frq_compare.png")
_docx_add_pagebreak(dh,)
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# COMPARISON OF ANCESTRIES")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "Ancestry comparison is performed against a HapMap3 reference panel using the program -bim2hapmap-. These plots are created from the *.eigenval files created using the --pca flag in plink. As part of the program we define a subset of individuals who are defined as like one or more of the HapMap3 populations. In this analysis the like population/s is/are ${ancestry_like}. This is based on similarity of the genotypes to HapMap reference genotypes. We flag individuals who, for the top-3 PCs, are no more than 2.5 standard deviations from the mean reported by the ${like} HapMap3 populations. Individuals are not removed but flagged in the ${path2file_file}-qc-${version}-${ancestry_like}-like.keep file. This can be used directly in plink using the --keep flag. The plots below are PC! vs. PC2; PC1 vs. PC3; PC2 vs. PC3). The top panel includes all individuals, whereas the bottom panel focuses on the regions around the ${ancestry_like} populations.")
_docx_paragraph_add_linebreak(dh)
_docx_image_add(dh,"..${delimit}${path2file_file}-qc-${version}${delimit}genotypeqc_data${delimit}bim2hapmap.png")
_docx_add_pagebreak(dh,)
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# CHROMOSOME DISTRIBUTIONS")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "Plotting the distribution of markers by chromosome is a useful sanity-check on your data to make sure all chromosomes were included in the final report.")
_docx_paragraph_add_linebreak(dh)
_docx_image_add(dh,"..${delimit}${path2file_file}-qc-${version}${delimit}genotypeqc_data${delimit}${path2file_file}-qc-${version}-hist-chromosomes.png")
_docx_add_pagebreak(dh,)
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# KINSHIP DISTRIBUTIONS")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "These plots are created from the *.kin0 files created using the --make-king-table flag in plink2. The following plots show relatedness as defined by this kinship matrix. Approximation of kinship thresholds (duplicates, 2nd and 3rd degree relatives) are given by horizontal red lines. As part of the quality control pipeline it was decided not to remove -related- individuals at this stage. The exception are individuals with excessive relatedness (indicative of genotyping error). The file ${path2file_file}-qc-${version}.relPairs can be used to define related pairs; or post-qc, an unrelated subset of a genotyping file can be created using the program -bim2unrelated-.")
_docx_paragraph_add_linebreak(dh)
_docx_image_add(dh,"..${delimit}${path2file_file}-qc-${version}${delimit}genotypeqc_data${delimit}${path2file_file}-qc-${version}-hist-KIN0_1.png")
_docx_paragraph_add_linebreak(dh)
_docx_image_add(dh,"..${delimit}${path2file_file}-qc-${version}${delimit}genotypeqc_data${delimit}${path2file_file}-qc-${version}-hist-KIN0_2.png")
_docx_add_pagebreak(dh,)
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# HETEROZYGOSITY DISTRIBUTIONS")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "These plots are created from the *.het files created using the --het flag in  plink. The --het flag computes observed and expected autosomal homozygous genotype counts for each sample, and reports method-of-moments F coefficient estimates i.e.")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, " ")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "([observed hom. count] - [expected count])")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "------------------------------------------")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "([total observations] - [expected count])")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, " ")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "Excessive heterozygosity can be indicative of mixed DNA samples; excessive homozygosity can be indicative of poor DNA quality and allele drop-out. In this pipeline, we exclude individuals whose rate of heterozygosity deviates from the population (of genotyping array) mean. Importantly, heterozygosity rates differ on genotyping arrays and within individuals of differing ancestries. Where there are mixed ancestry samples, you may consider relaxing the threshold and excluding only those individuals with extreme deviations from the sample mean.")
_docx_paragraph_add_linebreak(dh)
_docx_image_add(dh,"..${delimit}${path2file_file}-qc-${version}${delimit}genotypeqc_data${delimit}${path2file_file}-qc-${version}-hist-HET.png")
_docx_add_pagebreak(dh,)
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# HARDY WEINBERG DISTRIBUTIONS")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "These plots are created using the --hardy flag in plink. The --hardy flag writes a list of genotype-counts and Hardy-Weinberg equilibrium exact test statistics to plink.hwe. Importantly, we apply less stringent thresholds than in other routines as case samples, by design, may incur HW bias due to disease selection.")
_docx_paragraph_add_linebreak(dh)
_docx_image_add(dh,"..${delimit}${path2file_file}-qc-${version}${delimit}genotypeqc_data${delimit}${path2file_file}-qc-${version}-hist-HWE.png")
_docx_add_pagebreak(dh,)
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# MISSINGNESS BY INDIVIDUAL")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)	
_docx_paragraph_add_text(dh, "These plots are created using the --missing flag in plink. The missing --missing produces sample-based and variant-based missing data reports.")
_docx_paragraph_add_linebreak(dh)
_docx_image_add(dh,"..${delimit}${path2file_file}-qc-${version}${delimit}genotypeqc_data${delimit}${path2file_file}-qc-${version}-hist-IMISS.png")
_docx_add_pagebreak(dh,)
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# MISSINGNESS BY SNP")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "These plots are created using the --missing flag in plink. The missing --missing produces sample-based and variant-based missing data reports. As part of the pipeline we apply two --geno parameters during the QC pipeline to remove firstly excessive missing then completing the pipeline with a stricter limit.")
_docx_paragraph_add_linebreak(dh)
_docx_image_add(dh,"..${delimit}${path2file_file}-qc-${version}${delimit}genotypeqc_data${delimit}${path2file_file}-qc-${version}-hist-LMISS.png")
_docx_add_pagebreak(dh,)
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# ALLELE FREQUENCY")
_docx_paragraph_add_linebreak(dh)
_docx_paragraph_add_text(dh, "# =================================================================================")
_docx_paragraph_add_linebreak(dh) 
_docx_paragraph_add_text(dh, "These plots are created using the --freq counts flag. A standard mac 5 flag was added to version 5 of the QC report.")
_docx_paragraph_add_linebreak(dh)
_docx_image_add(dh,"..${delimit}${path2file_file}-qc-${version}${delimit}genotypeqc_data${delimit}${path2file_file}-qc-${version}-hist-FRQ.png")
_docx_paragraph_add_linebreak(dh)
// SAVING DOCX
_docx_save(dh, "..${delimit}${path2file_file}-qc-${version}${delimit}${path2file_file}-qc-${version}-quality-control-report.docx", 1)
_docx_close(dh)
end
